include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Error prevention
    - avoid_print
    - avoid_empty_else
    - avoid_relative_lib_imports
    - control_flow_in_finally
    - empty_statements
    - hash_and_equals
    - no_duplicate_case_values
    - prefer_void_to_null
    - unnecessary_statements
    - unrelated_type_equality_checks
    - valid_regexps
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - annotate_overrides
    - avoid_init_to_null
    - avoid_return_types_on_setters
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - close_sinks
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - file_names
    - library_names
    - library_prefixes
    - no_leading_underscores_for_local_identifiers
    - non_constant_identifier_names
    - package_api_docs
    - package_prefixed_library_names
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_single_quotes
    - sort_child_properties_last
    - type_init_formals
    - unawaited_futures
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_new
    - unnecessary_null_in_if_null_operators
    - unnecessary_this

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
